version: 1

merge:
  trigger:
    comments: ["!merge", "! merge"]
    branch_patterns: ["develop", "develop-.*"]

  ignore:  
    labels: ["status: WIP"]
    branch_patterns: ["main"]
  
  method: squash

  options: 
    squash: 
      title: "pull_request_title"
      body: "sumarize_commits"
  
  delete_after_merge: true