version: 1

merge:
  trigger:
    comments: ["!merge", "! merge"]

  ignore:  
    labels: ["status: WIP"]
    branch_patterns: ["poc/.*"]
  
  method: squash

  options: 
    squash: "pull_request_title"
    body: "sumarize_commits"
  
  delete_after_merge: true