# TODO: creates hotfix branch off of main
# - create branch off of main with hotfix-<major>.<minor>.X version number

name: Hotfix - Cut Branch

# Workflow runs when manually triggered using the UI or API
on: workflow_dispatch
 
jobs:
  cut-hotfix:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      with:
        ## This is a Personal Access Token from Admin User that allows us to bypass branch protections on develop
        token: ${{ secrets.PAT }}