# TODO: on merge to main from release (and patch?) branch
# - Create Tag (vX.X.X) on `main` branch
# - Create Github Release
# - upmerge develop from main (so develop has tag in history)
  # git checkout develop
  # git pull
  # git checkout main
  # git pull
  # git checkout develop
  # git merge main
  # git reset README.md
  # get checkout README.md
  # git commit -m "merge after release tag"

name: Release - Tag on Merge

on: 
  push:
    branches:
      - main

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      with:
        ## This is a Personal Access Token from Admin User that allows us to bypass branch protections on develop
        token: ${{ secrets.PAT }}