name: Verify Only Release/Hotfix PRs

on: 
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - main

jobs:
  # Only allow `release-*` or `hotfix-*` branches to merge to `main`
  verify-main:
    runs-on: ubuntu-latest

    steps:
    - name: "Verify Master PR are from 'release-*' or 'hotfix-*' branch"
      run: |
        if [[ ! $PR_BRANCH =~ $REGEXP ]]; then
          exit -1;
        fi
      env: 
        PR_BRANCH: ${{ github.head_ref }}
        REGEXP: (release|hotfix)-*