# Name should reflect when action occurs
name: Testing Cut Release

on:  workflow_dispatch
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cut-release:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      
    - name: Cut Release Branch
      # TODO: this still needs to be don
