# Name should reflect when action occurs
name: Verify PR Can Merge

# Workflow runs when manually triggered using the UI or API
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify-merge:
    runs-on: ubuntu-latest

    steps: 

    - name: "Get Branch Prefix"
      run: echo "##[set-output name=prefix;] $(echo $BRANCH_NAME | sed 's/\/.*//')"
      id: extract_branch
      env:
        BRANCH_NAME: ${{ github.head_ref }}
      
    - name: "Get PR Title"
      run: echo $BRANCH_PREFIX
      env:
        BRANCH_PREFIX: ${{ steps.extract_branch.outputs.prefix }}

    - name: "Verify PR Title Matches"
      run: "TBD: error if title does not match: `^<prefix>(optional scope): (1+ word description)*"