# Name should reflect when action occurs
name: Verify PR Can Merge

# Workflow runs when manually triggered using the UI or API
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify-merge:
    runs-on: ubuntu-latest

    steps: 

    - name: "Get Prefix"
      run: echo "##[set-output name=prefix;] $(echo $BRANCH_NAME | sed 's/\/.*//')"
      
    - name: "TBD: Verify that PR title matches regexp?"
      run: echo $BRANCH_PREFIX
      env:
        BRANCH_PREFIX: ${{ steps.extract_branch.outputs.prefix }}

      # get branch name
      # get prefix from branch name
      # get PR title
      # verify title matches `^<prefix>(optional scope): (\w\s)*