# Name should reflect when action occurs
name: Verify PR Can Merge

# Workflow runs when manually triggered using the UI or API
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify-pr-title:
    runs-on: ubuntu-latest

    steps:

    - name: "Get Branch Prefix"
      run: echo "##[set-output name=prefix;] $(echo $BRANCH_NAME | sed 's/\/.*//')"
      id: extract_branch
      env:
        BRANCH_NAME: ${{ github.head_ref }}
   
    - name: "Verify PR Title matches branch prefix (and conventional commit)"
      uses: deepakputhraya/action-pr-title@master
      with:
        regex: '(\([\w\s]*\)*\))?:[\w\s]*'
        allowed_prefixes:  ${{ steps.extract_branch.outputs.prefix }}
        prefix_case_sensitive: false
